---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue-niri
# description will be included in the image's metadata
description: A hardened niri desktop, built on secureblue.

base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: script
    snippets:
      - dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
      - rpm --import /usr/share/pki/rpm-gpg/secureblue.gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-terra44

  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - niri
        - xwayland-satellite
        - polkit-kde

        - greetd
        - greetd-selinux
        - noctalia-greeter
        - noctalia
        - ghostty
        - xdg-terminal-exec

        - swayidle
        - brightnessctl
        - playerctl
        - wl-mirror
        - wl-clipboard
        - cliphist
    remove:
      packages:
        - sway
        - sway-config-fedora
        - sddm
        - sddm-wayland-sway

  - type: systemd
    system:
      enabled:
        - greetd.service
      masked:
        - sddm.service
    user:
      enabled:
        - polkit-kde-authentication-agent-1.service
        - swayidle.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
